### ISSUE TITLE
Add the colormaps cmocean package

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-server#28]
Extending the matplotlib package with the colormaps provided by
https://matplotlib.org/cmocean/
to have nicer mapping.

**Comment by forman** [comment]
Well, not only they are "nicer", but also more useful from a scientific point of view as they have been been developed for ocean applications.

**Comment by AliceBalfanz** [comment]
Basically it is done (branch  alicja-28-add_cmocean_colorramp). 
When adding cmoceans to the miniconda environment, some packages are downgraded, e.g. scipy - is this an issue?

**Comment by forman** [comment]
It is an issue only, if the build is broken afterwards, e.g. unresolvable dependencies, unit tests fail, etc.

**Comment by AliceBalfanz** [comment]
This issue has been implemented with and already merged into master, thus it can be closed.
