### ISSUE TITLE
Enable colormapping using cmocean and _alpha

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube-server#48]
The usage of cmocean is not working, although the package is implemented. 
Furthermore when specifing a colorbar with _alpha, the variable is mapped as expected, but the legend image is not passed properly to the viewer.

**Comment by AliceBalfanz** [comment]
Colormapping with _aplha works fine, the viewer just needed a moment. In order to use the cmocean colorbars the color needs to be passed with the prefix 'cmo.' - e.g. to use the colorbar 'deep' one needs to specify 'cmo.deep'. But there is still an issue with the legend generation for the colormaps used from the cmocean package. Furthermore, it would be nice to find a way to ommit the 'cmo.' prefix.

**Comment by forman** [comment]
Why?

**Comment by forman** [comment]
Better avoid dropping the "cmo." prefix because it is a namespace identifier.
